import React, { useEffect, useState } from "react";
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from "react-redux";
import Cookies from 'js-cookie';
import Moralis from 'moralis'
import {
  getProducts,
  deleteProduct,
  addProduct,
  ApproveProduct,
  RejectProduct,
} from "../../redux/actions/productActions";
import Swal from "sweetalert2";
import "../components/GlobalVariable"
import { Table } from "reactstrap";
import Navsidebar from "../components/Navsidebar";
import Link from "next/dist/client/link";
import { useMoralis, useMoralisFile } from "react-moralis";
import Web3 from "web3";
import ProductTable from "../components/Product-Component/ProductTable";
import Head from "next/dist/shared/lib/head";
import { requireAuthenticationSA } from "../requireAuthenticationSA";

const Products = () => {
  const dispatch = useDispatch();
  const allProductsData = useSelector((state) => state.Products);
  const { loading, error, products } = allProductsData;

  // LOAD DATA
  useEffect(() => {
    dispatch(getProducts());
  }, []);

  const router = useRouter();
  const {errors}  = router.query;

  if(errors==405){
    Swal.fire(
      "Silahkan lengkapi profile",
      "Isi NIK sesuai dengan KTP anda",
      "warning"
  );
  }


  return (
    <>
    <Head>
      <title>Product</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <Navsidebar/>
    <main class="main-content position-relative border-radius-lg ">
    <div className="container-fluid py-1">
      <div className="row">
        <div className="col-12">
          <div className="card mt-3">
            <div className="card-header pb-0">
              <div className="row">
                <div className="col-6 d-flex align-items-center">
                  <h6 className="mb-0">Product Table</h6>
                </div>
                <div className="col-6 text-end">
                  <Link href={{ pathname: '/Product/SaveProduct'}}>
                    <a className="btn bg-button mb-0"><i className="fas fa-plus"></i>&nbsp;&nbsp;Add New Product</a>
                  </Link>
                </div>
              </div>
            </div>
            <div className="card-body px-0 pt-0 pb-2">
              <ProductTable ProductData={products} error={error} loading={loading}/>
            </div>
          </div>
        </div>
      </div>
    </div>
    </main>
    </body>
  </>
  );
};

export default Products;

export const getServerSideProps = requireAuthenticationSA(context => {
    return {props: {}}
})