import React, { useEffect, useState } from "react";
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from "react-redux";
import "../components/GlobalVariable"
import Navsidebar from "../components/Navsidebar";
import Link from "next/dist/client/link";
import VerifyTable from "../components/VerifyComponent/VerifyTable";
import Custompaginations from "../components/Pagination";
import { Input } from "reactstrap";
import { getVerifpaging } from "../../redux/actions/verifyAction";
import Cookies from 'js-cookie';
import Head from "next/dist/shared/lib/head";
import { requireAuthenticationSA } from "../requireAuthenticationSA";

const VerifyAdmin = () => {
  const dispatch = useDispatch();
  const allProductsData = useSelector((state) => state.Verifs);
  const { loading, error, verifs } = allProductsData;

  const router = useRouter()
  const {Page, Search}  = router.query;

  const handleSearch = (e) => {
    if (e.key === 'Enter') {
      location.href = "?Search=" + e.target.value;
    }
  };

  var Pagess = 0;
  var TotalDisplayed = 10;
  var sear = "";

  if(Page == null){
    Pagess = 1;
  }else{
    Pagess = Page;
  }

  if(Search != null){
    sear = Search;
  }

  // LOAD DATA
  useEffect(() => {
    dispatch(getVerifpaging(Pagess, TotalDisplayed, sear, Cookies.get("UserData")));
  }, []);

  return (
    <>
    <Head>
      <title>Verify Admin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={global.icon} />
    </Head>

    <body class="g-sidenav-show bg-gray-100">
    <div className="min-height-300 bg-primary position-absolute w-100"></div>
    <Navsidebar/>
    <main className="main-content position-relative border-radius-lg ">
    <div className="container-fluid py-1">
        
      <div className="row">
        <div className="col-12">
          <div className="card mt-3">
            <div className="card-header pb-0">
              <div className="row">
                <div className="col-9 d-flex align-items-center">
                  <h5 className="mb-0">Verify Seller</h5>
                </div>
                <div className="col-3 text-end">
                  <div className="input-group mb-4">
                    <span className="input-group-text"><i className="fa-solid fa-magnifying-glass"></i></span>
                    <Input onKeyDown={handleSearch}  placeholder="Search by Address" defaultValue={sear != "" ? sear : null} className="form-control"/>
                  </div>
                </div>
              </div>
            </div>
            <div className="card-body px-0 pt-0 pb-2">
              <VerifyTable ProductData={verifs} error={error} loading={loading}/>
            </div>
          </div>
          <br/>
          <Custompaginations PageNow={Pagess} TotalDisplayed={TotalDisplayed} TotalProduct={verifs.intTotalData} isRouterQuery={sear != "" ? true : false}/>
        </div>
      </div>
    </div>
    </main>
    </body>
    </> 
  );
};

export default VerifyAdmin;

export const getServerSideProps = requireAuthenticationSA(context => {
    return {props: {}}
})