import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <section className="article">
        <h1>Welcome Admin</h1>
      </section>
    </div>
  );
}
